apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  namespace: artifactory 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: postgresql-service.artifactory.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: artifactory
            - name: DB_USERNAME
              value: artifactory
            - name: DB_PASSWORD
              value: Passw0rd
          volumeMounts:
            - name: artifactory-data
              mountPath: /var/opt/jfrog/artifactory
      volumes:
        - name: artifactory-data
          persistentVolumeClaim:
            claimName: jfrog
